services:
  - type: web
    name: bitespeed-api
    runtime: node
    buildCommand: npm install && npm run build && npm run prisma:push
    startCommand: npm start
    plan: free
    region: ohio
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: bitespeed-db
          envVarKey: DATABASE_URL
      - key: PORT
        value: 3000

  - type: postgres
    name: bitespeed-db
    plan: free
    region: ohio
    initialDbName: bitespeed
